import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { materializeUserIiiConfig } from "../src/cli/iii-config.js";

// Mirrors the bundled iii-config.yaml shape: at least one `state_store.db`
// line and one `stream_store` line, both using the relative `./data/`
// prefix. Includes a comment to verify comments survive the regex pass
// untouched (`js-yaml` would have lost them).
const BUNDLED_FIXTURE = `workers:
  - name: iii-http
    config:
      port: 3111
  - name: iii-state
    config:
      adapter:
        name: kv
        config:
          store_method: file_based
          file_path: ./data/state_store.db
  - name: iii-stream
    config:
      port: 3112
      adapter:
        name: kv
        config:
          store_method: file_based
          file_path: ./data/stream_store
  - name: iii-observability
    config:
      # sampling_ratio: keep at 0.1 to avoid the 137 GB log feedback
      # loop documented in #519.
      sampling_ratio: 0.1
`;

let sandbox: string;
let bundledPath: string;
let targetDir: string;
let dataDir: string;

beforeEach(() => {
  sandbox = mkdtempSync(join(tmpdir(), "agentmemory-iii-config-"));
  bundledPath = join(sandbox, "bundled-iii-config.yaml");
  targetDir = join(sandbox, "home", ".agentmemory", "config");
  dataDir = join(sandbox, "home", ".agentmemory", "data");
  writeFileSync(bundledPath, BUNDLED_FIXTURE, "utf-8");
});

afterEach(() => {
  rmSync(sandbox, { recursive: true, force: true });
});

describe("materializeUserIiiConfig", () => {
  it("materializes the config with absolute data paths on first call", () => {
    const result = materializeUserIiiConfig({
      targetDir,
      dataDir,
      findBundled: () => bundledPath,
    });

    expect(result).toBe(join(targetDir, "iii-config.yaml"));
    const written = readFileSync(result!, "utf-8");

    // Relative paths replaced with absolute.
    expect(written).toContain(`file_path: ${dataDir}/state_store.db`);
    expect(written).toContain(`file_path: ${dataDir}/stream_store`);
    expect(written).not.toContain("file_path: ./data/state_store.db");
    expect(written).not.toContain("file_path: ./data/stream_store");

    // Header inserted.
    expect(written.startsWith("# Generated by agentmemory")).toBe(true);
    expect(written).toContain(`# Source: ${bundledPath}`);

    // Substantive bundled comments survive (regex-based rewrite, no YAML round-trip).
    expect(written).toContain("# sampling_ratio: keep at 0.1");
    expect(written).toContain("sampling_ratio: 0.1");
  });

  it("is idempotent — second call returns the same path without rewriting", () => {
    const first = materializeUserIiiConfig({
      targetDir,
      dataDir,
      findBundled: () => bundledPath,
    });
    expect(first).not.toBeNull();
    const firstMtime = statSync(first!).mtimeMs;
    const firstBody = readFileSync(first!, "utf-8");

    // Even if a different bundled is offered, materialize must NOT
    // overwrite the existing user file.
    const otherBundled = join(sandbox, "other.yaml");
    writeFileSync(otherBundled, "DIFFERENT CONTENT\n", "utf-8");

    const second = materializeUserIiiConfig({
      targetDir,
      dataDir,
      findBundled: () => otherBundled,
    });
    expect(second).toBe(first);
    expect(statSync(second!).mtimeMs).toBe(firstMtime);
    expect(readFileSync(second!, "utf-8")).toBe(firstBody);
  });

  it("copies verbatim (with header) when the bundled shape is not recognized", () => {
    const unrecognized = join(sandbox, "unrecognized.yaml");
    const body = "workers: []\n# no state_store / stream_store keys here\n";
    writeFileSync(unrecognized, body, "utf-8");

    const warnings: string[] = [];
    const result = materializeUserIiiConfig({
      targetDir,
      dataDir,
      findBundled: () => unrecognized,
      onWarn: (msg) => warnings.push(msg),
    });

    expect(result).not.toBeNull();
    const written = readFileSync(result!, "utf-8");
    expect(written).toContain(body);
    expect(written.startsWith("# Generated by agentmemory")).toBe(true);
    expect(warnings.some((m) => m.includes("unrecognized bundled shape"))).toBe(true);
  });

  it("returns null when no bundled config can be located", () => {
    const result = materializeUserIiiConfig({
      targetDir,
      dataDir,
      findBundled: () => null,
    });
    expect(result).toBeNull();
    expect(existsSync(join(targetDir, "iii-config.yaml"))).toBe(false);
  });

  it("does not throw on a read-only target directory; returns null", () => {
    // Pre-create the target dir read-only so mkdirSync (recursive) is a
    // no-op for the dir but openSync of the .tmp file fails with EACCES.
    mkdirSync(targetDir, { recursive: true });
    const warnings: string[] = [];
    try {
      // 0o500 = read+execute only, no write.
      const { chmodSync } = require("node:fs");
      chmodSync(targetDir, 0o500);

      const result = materializeUserIiiConfig({
        targetDir,
        dataDir,
        findBundled: () => bundledPath,
        onWarn: (msg) => warnings.push(msg),
      });

      expect(result).toBeNull();
      expect(existsSync(join(targetDir, "iii-config.yaml"))).toBe(false);
      expect(warnings.length).toBeGreaterThan(0);
    } finally {
      const { chmodSync } = require("node:fs");
      chmodSync(targetDir, 0o700);
    }
  });

  it("parallel callers do not corrupt the file", async () => {
    const results = await Promise.all([
      Promise.resolve().then(() =>
        materializeUserIiiConfig({
          targetDir,
          dataDir,
          findBundled: () => bundledPath,
        }),
      ),
      Promise.resolve().then(() =>
        materializeUserIiiConfig({
          targetDir,
          dataDir,
          findBundled: () => bundledPath,
        }),
      ),
    ]);
    expect(results[0]).toBe(results[1]);
    const written = readFileSync(results[0]!, "utf-8");
    expect(written).toContain(`file_path: ${dataDir}/state_store.db`);
    expect(written).toContain(`file_path: ${dataDir}/stream_store`);
  });
});
