{{- if include "agentmemory.hasManagedSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentmemory.fullname" . }}
  labels:
    {{- include "agentmemory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.agentmemorySecret }}
  {{ .Values.secret.keys.hmac }}: {{ .Values.secret.agentmemorySecret | quote }}
  {{- end }}
{{- end }}
