// First-start materialization of the user-anchored iii-engine config.
//
// Two problems this fixes:
//   1. Bundled `iii-config.yaml` declares `file_path: ./data/...`
//      (relative). When `iii --config <path>` runs with a different
//      cwd, the KV state and stream store land wherever cwd points —
//      users end up with `~/Tara/data`, `~/data`, etc. instead of a
//      single global location. Rewriting to absolute paths under
//      ~/.agentmemory/data/ makes the engine location-independent.
//   2. iii's config watcher (Rust `notify` crate, NonRecursive)
//      watches the PARENT directory of the config file. With the
//      config at ~/.agentmemory/iii-config.yaml, every write to
//      sibling files (preferences.json, iii.pid, worker.pid,
//      engine-state.json) triggers a config reload, which drops the
//      worker's HTTP function registrations → 404 on every
//      /agentmemory/* route → blank viewer. Putting the materialized
//      config in a quiet ~/.agentmemory/config/ subdir sidesteps
//      this.
//
// The implementation is intentionally small and pure: it takes the
// target dir, the data dir to anchor paths to, and a `findBundled`
// resolver — no implicit dependency on prefsDir() / __dirname. The
// thin caller in cli.ts wires those values; tests inject their own.
//
// Behavior contract:
//   - Idempotent: if `<targetDir>/iii-config.yaml` already exists,
//     return its path without touching the file.
//   - Shape-guarded rewrite: only rewrite paths if the recognizable
//     bundled markers are present. Otherwise copy verbatim — never
//     silently corrupt a user-supplied template.
//   - Atomic write: tmp + fsync + rename, mirroring writePrefs() in
//     `./preferences.ts`. Parallel callers either both succeed (with
//     identical content) or one wins; never a half-written file.
//   - Best-effort: any failure (read-only $HOME, missing bundled,
//     permission denied) calls onWarn and returns null. Callers
//     fall through to legacy candidates and the engine still starts.

import {
  closeSync,
  existsSync,
  fsyncSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  writeSync,
} from "node:fs";
import { join } from "node:path";

export interface MaterializeOptions {
  // Where to write the materialized config, e.g. ~/.agentmemory/config
  targetDir: string;
  // Absolute data dir to substitute for relative `./data/` paths,
  // e.g. ~/.agentmemory/data
  dataDir: string;
  // Resolver for the bundled template path. Returning null disables
  // materialization (caller falls through to legacy candidates).
  findBundled: () => string | null;
  // Best-effort log sink for non-fatal failures.
  onWarn?: (msg: string) => void;
}

const STATE_STORE_MARKER = "file_path: ./data/state_store.db";
const STREAM_STORE_MARKER = "file_path: ./data/stream_store";
const RELATIVE_DATA_PATH = /file_path:\s*\.\/data\//g;

export function materializeUserIiiConfig(
  opts: MaterializeOptions,
): string | null {
  const { targetDir, dataDir, findBundled, onWarn } = opts;
  const warn = onWarn ?? (() => {});

  try {
    const userPath = join(targetDir, "iii-config.yaml");
    if (existsSync(userPath)) return userPath;

    const bundled = findBundled();
    if (!bundled) return null;

    const raw = readFileSync(bundled, "utf-8");

    const recognized =
      raw.includes(STATE_STORE_MARKER) && raw.includes(STREAM_STORE_MARKER);

    const body = recognized
      ? raw.replace(RELATIVE_DATA_PATH, `file_path: ${dataDir}/`)
      : raw;
    if (!recognized) {
      warn(
        `materializeUserIiiConfig: unrecognized bundled shape at ${bundled}, copying verbatim`,
      );
    }

    const header =
      `# Generated by agentmemory on first start. Edit freely;\n` +
      `# agentmemory will not overwrite unless this file is deleted.\n` +
      `# Source: ${bundled}\n`;

    mkdirSync(targetDir, { recursive: true });
    const tmp = `${userPath}.${process.pid}.tmp`;
    const fd = openSync(tmp, "w", 0o600);
    try {
      writeSync(fd, header + body);
      try {
        fsyncSync(fd);
      } catch {
        // fsync isn't available on every filesystem (some Docker
        // overlays). The rename below is still atomic; we just
        // can't guarantee durability against a power loss.
      }
    } finally {
      closeSync(fd);
    }
    renameSync(tmp, userPath);
    return userPath;
  } catch (err) {
    warn(
      `materializeUserIiiConfig: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return null;
  }
}
